trigger:
  branches:
    include: ['master']
  tags:
    include: ['*']

jobs:
  - job: 'Build'
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
    strategy:
      matrix:
        windows-stable:
          imageName: 'windows-latest'
          rustup_toolchain: stable
          target: x86_64-pc-windows-msvc
        mac-stable:
          imageName: 'macos-latest'
          rustup_toolchain: stable
          target: x86_64-apple-darwin
        linux-stable:
          imageName: 'ubuntu-latest'
          rustup_toolchain: stable
          target: x86_64-unknown-linux-musl
    pool:
      vmImage: $(imageName)
    steps:
      - script: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain $RUSTUP_TOOLCHAIN
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: "Install rust (*nix)"
        condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y --profile minimal --default-toolchain %RUSTUP_TOOLCHAIN%
          set PATH=%PATH%;%USERPROFILE%\.cargo\bin
          echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
        displayName: "Install rust (windows)"
        condition: eq(variables['Agent.OS'], 'Windows_NT')
      - bash: |
          rustup default $RUSTUP_TOOLCHAIN
          rustup update $RUSTUP_TOOLCHAIN
        displayName: "Set correct Rust version"
      - bash: |
          rustup target add x86_64-unknown-linux-musl
        displayName: "Add x86_64-unknown-linux-musl target"
        condition: eq(variables['Agent.OS'], 'Linux')
      - bash: |
          DATE="$(date +%Y-%m-%d)"
          echo $DATE
          echo "##vso[task.setvariable variable=build.date]$DATE"
        displayName: "Create date variable"
      - bash: |
          MY_TAG="$(Build.SourceBranch)"
          MY_TAG=${MY_TAG#refs/tags/}
          echo $MY_TAG
          echo "##vso[task.setvariable variable=build.my_tag]$MY_TAG"
        displayName: "Create my tag variable"
      - bash: |
          cargo build --release --all --target $TARGET
        displayName: Build (*nix)
      - task: CopyFiles@2
        displayName: Copy assets (windows)
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/target/$(TARGET)/release'
          contents: durse.exe
          targetFolder: '$(Build.BinariesDirectory)/durse'
        condition: eq(variables['Agent.OS'], 'Windows_NT')
      - task: CopyFiles@2
        displayName: Copy assets (*nix)
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/target/$(TARGET)/release'
          contents: durse
          targetFolder: '$(Build.BinariesDirectory)/durse'
        condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
      - task: ArchiveFiles@2
        displayName: Gather assets (*nix)
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)/durse'
          archiveType: 'tar'
          tarCompression: 'gz'
          archiveFile: '$(Build.ArtifactStagingDirectory)/durse-$(build.my_tag)-$(TARGET).tar.gz'
        condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
      - task: ArchiveFiles@2
        displayName: Gather assets (windows)
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)/durse'
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/durse-$(build.my_tag)-$(TARGET).zip'
        condition: eq(variables['Agent.OS'], 'Windows_NT')
      - task: GithubRelease@0
        displayName: Github Release
        condition: succeeded()
        inputs:
          gitHubConnection: 'github.com_curtisalexander'
          repositoryName: 'curtisalexander/durse-rs'
          action: 'edit'
          target: '$(build.sourceVersion)'
          tagSource: 'manual'
          tag: '$(build.my_tag)'
          assets: '$(Build.ArtifactStagingDirectory)/durse-$(build.my_tag)-$(TARGET).tar.gz'
          title: '$(build.my_tag) - $(build.date)'
          assetUploadMode: 'replace'
          addChangeLog: false